spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gimyujin998@gmail.com
    password: rladbwls12!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

  datasource:
    master:
      jdbc-url: jdbc:mariadb://192.0.200.90:3306/a123
      driver-class-name: org.mariadb.jdbc.Driver
      username: ujk
      password: qwer1234
    slave:
      jdbc-url: jdbc:mariadb://192.0.2.61:3306/a123
      driver-class-name: org.mariadb.jdbc.Driver
      username: ujk
      password: qwer1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
